#Task 1

In [ ]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [ ]:
#Temp, Rain, Humidity
inputs = np.array([[73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70]], dtype='float32')

In [ ]:
#yield prediction of apple
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

In [ ]:
data = torch.from_numpy(inputs)
labels = torch.from_numpy(targets)
print(data)
print(labels)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
print(data.size())
print(labels.size())

torch.Size([5, 3])
torch.Size([5, 1])


In [ ]:
n=data.size()[1] #number of features
#weights and bias
w = torch.zeros(1,n,requires_grad=True)
b = torch.zeros(1,requires_grad=True)
print(w)
print(b)
print(w.size())
print(b.size())

tensor([[0., 0., 0.]], requires_grad=True)
tensor([0.], requires_grad=True)
torch.Size([1, 3])
torch.Size([1])


In [ ]:
#Defining model
def model(X):
  return X @ w.t() + b

In [ ]:
#Generating Predictions
y_predict = model(data)
print("Predictions: ", y_predict)
print("\nActual Targets: ", labels)

Predictions:  tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

Actual Targets:  tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
#MSE loss
def MSEloss(predictions,targets):
  diff= predictions-targets
  return torch.sum(diff*diff)/diff.numel()

In [ ]:
#Computing loss
print("Loss: ", MSEloss(y_predict,labels))

Loss:  tensor(6990.2002, grad_fn=<DivBackward0>)


In [ ]:
#Computing gradients
epochs = 100
learning_rate = 0.00005

for i in range(epochs):
  preds = model(data)
  loss = MSEloss(preds,labels)
  loss.backward()
  with torch.no_grad():
        print(w.grad, '\n', b.grad)
        w -= w.grad * learning_rate
        b -= b.grad * learning_rate
        w.grad.zero_()
        b.grad.zero_()
  print(f"Epoch {i}/{epochs}: Loss: {loss}")

tensor([[-12465.2002, -15064.0010,  -9007.2002]]) 
 tensor([-152.4000])
Epoch 0/100: Loss: 6990.2001953125
tensor([[11386.0146, 10664.1279,  6847.7070]]) 
 tensor([130.7685])
Epoch 1/100: Loss: 4510.54443359375
tensor([[-7574.1211, -9603.6016, -5681.8125]]) 
 tensor([-93.8790])
Epoch 2/100: Loss: 2943.03466796875
tensor([[7333.2314, 6503.7153, 4238.5996]]) 
 tensor([83.1719])
Epoch 3/100: Loss: 1948.142578125
tensor([[-4541.1514, -6164.5552, -3598.2659]]) 
 tensor([-57.4587])
Epoch 4/100: Loss: 1313.21728515625
tensor([[4772.6519, 3922.5488, 2609.3716]]) 
 tensor([53.2176])
Epoch 5/100: Loss: 905.0109252929688
tensor([[-2667.3223, -3992.9026, -2291.9531]]) 
 tensor([-34.8409])
Epoch 6/100: Loss: 639.9791259765625
tensor([[3148.6641, 2326.6887, 1592.8285]]) 
 tensor([34.3222])
Epoch 7/100: Loss: 465.69134521484375
tensor([[-1515.7661, -2616.6245, -1472.1797]]) 
 tensor([-20.8374])
Epoch 8/100: Loss: 349.2040100097656
tensor([[2113.3088, 1344.8997,  959.2972]]) 
 tensor([22.3647])
Epoch 

In [ ]:
# Generate predictions
preds = model(data)
print("Prediction is : ", preds)
print("\nActual targets is : ", labels)
print("Loss is : ", MSEloss(preds, labels))

Prediction is :  tensor([[ 57.3052],
        [ 81.1254],
        [120.9276],
        [ 21.7772],
        [ 99.6329]], grad_fn=<AddBackward0>)

Actual targets is :  tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
Loss is :  tensor(3.3643, grad_fn=<DivBackward0>)


#Using libraries

In [ ]:
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
import torch.nn.functional as F

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119], 
                    [56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119], 
                    [56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]],dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
data= TensorDataset(inputs,targets)

In [ ]:
# Define data loader
train_loader = DataLoader(data, batch_size = 3, shuffle = True)

In [ ]:
# Defining model
def model(X):
    return X @ w.t() + b

In [ ]:
#Defining Parameters
w = torch.zeros(2, 3, requires_grad=True)
b = torch.zeros(2, requires_grad=True)

In [ ]:
learning_rate = 0.00001
optimizer = torch.optim.SGD([w, b], lr = learning_rate, momentum = 0.9)

In [ ]:
# Define loss function
loss_fn = F.mse_loss

In [ ]:
#Function to train model
def fit(epochs, optimizer, model, loss_fn, w, b):
  for i in range(epochs):
      for x,y in train_loader:
          optimizer.zero_grad()
          preds = model(x)
          loss = loss_fn(preds, y)
          loss.backward()
          with torch.no_grad():
              w -= w.grad * learning_rate
              b -= b.grad * learning_rate
              w.grad.zero_()
              b.grad.zero_()
          optimizer.step()
      print(f"Epoch {i}/{epochs}: Loss: {loss}")

In [ ]:
#Training model for 100 epochs
fit(100, optimizer, model, loss_fn, w, b)

Epoch 0/100: Loss: 511.5111083984375
Epoch 1/100: Loss: 1063.9200439453125
Epoch 2/100: Loss: 234.48399353027344
Epoch 3/100: Loss: 365.9972229003906
Epoch 4/100: Loss: 557.9973754882812
Epoch 5/100: Loss: 73.47393035888672
Epoch 6/100: Loss: 441.7743225097656
Epoch 7/100: Loss: 16.546804428100586
Epoch 8/100: Loss: 140.7797393798828
Epoch 9/100: Loss: 58.26425552368164
Epoch 10/100: Loss: 321.1194152832031
Epoch 11/100: Loss: 391.1067199707031
Epoch 12/100: Loss: 289.2616271972656
Epoch 13/100: Loss: 51.03975296020508
Epoch 14/100: Loss: 567.3075561523438
Epoch 15/100: Loss: 236.41514587402344
Epoch 16/100: Loss: 215.1763458251953
Epoch 17/100: Loss: 117.39156341552734
Epoch 18/100: Loss: 259.5453186035156
Epoch 19/100: Loss: 182.32212829589844
Epoch 20/100: Loss: 18.01908302307129
Epoch 21/100: Loss: 166.66380310058594
Epoch 22/100: Loss: 16.725130081176758
Epoch 23/100: Loss: 194.20851135253906
Epoch 24/100: Loss: 179.72508239746094
Epoch 25/100: Loss: 290.697265625
Epoch 26/100: Lo

In [ ]:
# Generate predictions and compare with targets
preds = model(inputs)
print("Prediction is : ", preds)
print("\nActual targets is : ", targets)
print("Loss is : ", loss_fn(preds, targets))

Prediction is :  tensor([[ 57.7065,  70.9615],
        [ 80.7573,  98.4005],
        [121.4506, 137.6227],
        [ 23.7822,  40.0954],
        [ 97.7986, 113.3523],
        [ 57.7065,  70.9615],
        [ 80.7573,  98.4005],
        [121.4506, 137.6227],
        [ 23.7822,  40.0954],
        [ 97.7986, 113.3523],
        [ 57.7065,  70.9615],
        [ 80.7573,  98.4005],
        [121.4506, 137.6227],
        [ 23.7822,  40.0954],
        [ 97.7986, 113.3523]], grad_fn=<AddBackward0>)

Actual targets is :  tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
Loss is :  tensor(10.9737, grad_fn=<MseLossBackward0>)
