In [ ]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [ ]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']

In [ ]:
le = preprocessing.LabelEncoder()
weather_encoded=le.fit_transform(weather)
print("Weather:" ,weather_encoded) # 0-overcast 1-rainy 2-sunny

Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [ ]:
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Temp:",temp_encoded) #0-cool 1-hot 2-mild
print("Play:",label) #0-no 1-yes

Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
features=tuple(zip(weather_encoded,temp_encoded))
print("Features:",features)

Features: ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [ ]:
#Creating a classifier
model=MultinomialNB()
# Train the model using the training sets
model.fit(features,label)


MultinomialNB()

In [ ]:
predicted = model.predict([[1,2]]) # 1: rainy and 2:mild
print("Predicted value: ", predicted) #1-play  false prediction

Predicted value:  [1]


In [ ]:
predicted = model.predict([[0,1]]) 
print("Predicted value: ", predicted)

Predicted value:  [1]


In [ ]:
predicted = model.predict([[2,2]]) # 
print("Predicted value: ", predicted)

Predicted value:  [1]


In [ ]:
predicted = model.predict([[2,1]]) # 1: rainy and 2:mild
print("Predicted value: ", predicted)

Predicted value:  [1]


In [ ]:
print(model.get_params())

{'alpha': 1.0, 'class_prior': None, 'fit_prior': True}


# Gaussian Naive Bayes

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris= datasets.load_iris()

In [ ]:
print("Features: ",iris.feature_names)
print("\nTarget: ",iris.target_names) 

print("\nData shape: ", iris.data.shape)
print("\n target shape: ", iris.target.shape)

X= iris.data[:,:]
Y= iris.target[:]


Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target:  ['setosa' 'versicolor' 'virginica']

Data shape:  (150, 4)

 target shape:  (150,)


In [ ]:
from sklearn.model_selection import train_test_split
#split data set into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X,
Y, test_size = 0.30, random_state = 5)

In [ ]:
import numpy as np
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, Y_train)

#Predict the response for test dataset
Y_pred = gnb.predict(X_test)


In [ ]:
Y_pred

array([1, 1, 2, 0, 2, 1, 0, 2, 0, 1, 1, 1, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 0, 1, 0, 0, 2, 0, 2, 2, 1, 0, 0,
       1])

In [ ]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))

Accuracy: 0.9333333333333333


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, Y_pred)

array([[15,  0,  0],
       [ 0, 15,  1],
       [ 0,  2, 12]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(Y_test, Y_pred, average=None)
recall = recall_score(Y_test, Y_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.         0.88235294 0.92307692]
recall: [1.         0.9375     0.85714286]


# Exercise

# Dataset3 Task1

In [ ]:
from sklearn import datasets
import pandas as pd
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Datasets/Dataset3.csv')
data.head()

Outlook Temp Wind  Humidity  Class
0       R    H    F         1      0
1       R    H    T         2      0
2       O    H    F         1      1
3       R    M    F         1      1
4       S    C    F         1      1

In [ ]:
X_d3= data.iloc[:,:-1].values
Y_d3= data.iloc[:,-1].values
print("Input: ", X_d3)
print("\nOutput: ",Y_d3)

Input:  [['R' 'H' 'F' 1]
 ['R' 'H' 'T' 2]
 ['O' 'H' 'F' 1]
 ['R' 'M' 'F' 1]
 ['S' 'C' 'F' 1]
 ['O' 'C' 'T' 0]
 ['O' 'C' 'T' 1]
 ['R' 'M' 'F' 1]
 ['O' 'C' 'F' 0]
 ['S' 'M' 'F' 2]
 ['R' 'C' 'T' 2]
 ['O' 'M' 'T' 0]
 ['O' 'H' 'F' 1]
 ['S' 'M' 'T' 1]]

Output:  [0 0 1 1 1 0 1 0 1 1 0 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

dummy = pd.get_dummies(data, columns = ['Outlook', 'Temp', 'Wind'])
print('\nDummy: \n', dummy)


Dummy: 
     Humidity  Class  Outlook_O  Outlook_R  ...  Temp_H  Temp_M  Wind_F  Wind_T
0          1      0          0          1  ...       1       0       1       0
1          2      0          0          1  ...       1       0       0       1
2          1      1          1          0  ...       1       0       1       0
3          1      1          0          1  ...       0       1       1       0
4          1      1          0          0  ...       0       0       1       0
5          0      0          1          0  ...       0       0       0       1
6          1      1          1          0  ...       0       0       0       1
7          1      0          0          1  ...       0       1       1       0
8          0      1          1          0  ...       0       0       1       0
9          2      1          0          0  ...       0       1       1       0
10         2      0          0          1  ...       0       0       0       1
11         0      1          1          0 

In [ ]:
dummy = dummy.drop(['Class'], axis=1)
df=dummy
print('Final Data: \n\n', df)

Final Data: 

     Humidity  Outlook_O  Outlook_R  Outlook_S  ...  Temp_H  Temp_M  Wind_F  Wind_T
0          1          0          1          0  ...       1       0       1       0
1          2          0          1          0  ...       1       0       0       1
2          1          1          0          0  ...       1       0       1       0
3          1          0          1          0  ...       0       1       1       0
4          1          0          0          1  ...       0       0       1       0
5          0          1          0          0  ...       0       0       0       1
6          1          1          0          0  ...       0       0       0       1
7          1          0          1          0  ...       0       1       1       0
8          0          1          0          0  ...       0       0       1       0
9          2          0          0          1  ...       0       1       1       0
10         2          0          1          0  ...       0       0      

In [ ]:
X_encoded_d3= df.iloc[:,:]
X_encoded_d3

Humidity  Outlook_O  Outlook_R  Outlook_S  ...  Temp_H  Temp_M  Wind_F  Wind_T
0          1          0          1          0  ...       1       0       1       0
1          2          0          1          0  ...       1       0       0       1
2          1          1          0          0  ...       1       0       1       0
3          1          0          1          0  ...       0       1       1       0
4          1          0          0          1  ...       0       0       1       0
5          0          1          0          0  ...       0       0       0       1
6          1          1          0          0  ...       0       0       0       1
7          1          0          1          0  ...       0       1       1       0
8          0          1          0          0  ...       0       0       1       0
9          2          0          0          1  ...       0       1       1       0
10         2          0          1          0  ...       0       0       0       1
11         0          1          0          0  ...       0       1       0       1
12         1          1          0          0  ...       1       0       1       0
13         1          0          0          1  ...       0       1       0       1

[14 rows x 9 columns]

In [ ]:
print(Y_d3.shape)
print(X_encoded_d3.shape)

(14,)
(14, 9)


In [ ]:
X_train_d3, X_test_d3, Y_train_d3, Y_test_d3 = train_test_split(X_encoded_d3,
Y_d3, test_size = 0.15, random_state = 121)

In [ ]:
model_d3 = MultinomialNB()

model_d3.fit(X_train_d3, Y_train_d3)

Y_pred_d3 = model_d3.predict(X_test_d3)

In [ ]:
from sklearn.metrics import confusion_matrix, precision_score, accuracy_score, f1_score, recall_score

In [ ]:
model_d3.get_params()

print(model_d3.get_params())

{'alpha': 1.0, 'class_prior': None, 'fit_prior': True}


In [ ]:
print('Confusion Matrix: \n', confusion_matrix(Y_test_d3, Y_pred_d3))
print('\n\nAccuracy: ', accuracy_score(Y_test_d3,Y_pred_d3))

print('\n\nPrecision: ', precision_score(Y_test_d3,Y_pred_d3))

print('\n\nRecall : ', recall_score(Y_test_d3,Y_pred_d3))

print('\n\nF1 score: ', f1_score(Y_test_d3,Y_pred_d3))


Confusion Matrix: 
 [[0 1]
 [0 2]]


Accuracy:  0.6666666666666666


Precision:  0.6666666666666666


Recall :  1.0


F1 score:  0.8


In [ ]:
print(X_test_d3)

    Humidity  Outlook_O  Outlook_R  Outlook_S  ...  Temp_H  Temp_M  Wind_F  Wind_T
7          1          0          1          0  ...       0       1       1       0
9          2          0          0          1  ...       0       1       1       0
12         1          1          0          0  ...       1       0       1       0

[3 rows x 9 columns]


In [ ]:
predicted_1 = model_d3.predict([[1,0,1,0,0,0,1,1,0]])  #Humidity =’Normal’(1), Outlook='Rainy'(0,1,0), Temp='Mild'(0,0,1), Wind = 'False'(1,0)
print(predicted_1) 

[1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
predicted_2 = model_d3.predict([[2,0,0,1,1,0,0,0,1]])  #Humidity =’High’(2), Outlook='Sunny'(0,0,1), Temp='Cool'(1,0,0), Wind = 'True'(0,1)
print(predicted_2) 

[0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  "X does not have valid feature names, but"


# Task 2 wine dataset

In [ ]:
wine=datasets.load_wine()
print("Features: ", wine.feature_names)
print("\nTarget: ", wine.target_names )

print("Shape: ", wine.data.shape[1])


Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']

Target:  ['class_0' 'class_1' 'class_2']
Shape:  13


In [ ]:
X_wine= wine.data[:,:]
print(X_wine.shape)
print(X_wine)

(178, 13)
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [ ]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
le = preprocessing.LabelEncoder()
X_encoded_wine = np.empty([X_wine.shape[0],X_wine.shape[1]])
for i in range(wine.data.shape[1]):
  X_encoded_wine[i]=le.fit_transform(X_wine[i])

print('X_encoded_wine: \n')
print(X_encoded_wine)

print('\n')
print('X_wine :\n')
print(X)

X_encoded_wine: 

[[9.00000000e+000 2.00000000e+000 4.00000000e+000 ... 1.00000000e+000
  7.00000000e+000 1.20000000e+001]
 [1.00000000e+001 3.00000000e+000 4.00000000e+000 ... 1.00000000e+000
  7.00000000e+000 1.20000000e+001]
 [9.00000000e+000 2.00000000e+000 3.00000000e+000 ... 1.00000000e+000
  6.00000000e+000 1.20000000e+001]
 ...
 [3.68015657e+180 1.12547024e-153 2.99696928e+161 ... 2.52301636e-258
  4.47593804e-091 6.01334512e-154]
 [6.97379661e+228 8.18432962e-085 1.10872384e+219 ... 4.29058029e+270
  1.96086529e+243 7.58094500e-096]
 [9.58659700e+140 6.01347002e-154 1.98795669e-062 ... 9.13544126e+242
  3.84586715e-086 9.91600230e-096]]


X_wine :

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1

In [ ]:
Y_wine = wine.target[:]
print(Y_wine)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [ ]:
#with encoding
X_train_wine, X_test_wine, Y_train_wine, Y_test_wine = train_test_split(X_encoded_wine,
Y_wine, test_size = 0.34, random_state = 121)

In [ ]:
gnb_wine = GaussianNB()

#Train the model using the training sets
gnb_wine.fit(X_train_wine, Y_train_wine)

#Predict the response for test dataset
Y_pred_wine = gnb_wine.predict(X_test_wine)

/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:205: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:490: RuntimeWarning: overflow encountered in square
  n_ij -= 0.5 * np.sum(((X - self.theta_[i, :]) ** 2) / (self.var_[i, :]), 1)
/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:490: RuntimeWarning: invalid value encountered in true_divide
  n_ij -= 0.5 * np.sum(((X - self.theta_[i, :]) ** 2) / (self.var_[i, :]), 1)


In [ ]:
print(Y_pred_wine)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
print('Confusion matrix: \n', confusion_matrix(Y_test_wine,Y_pred_wine))

print("\n\nAccuracy:",metrics.accuracy_score(Y_test_wine, Y_pred_wine))

print("\n\nPrecision:",precision_score(Y_test_wine, Y_pred_wine, average=None))
print("\nRecall:",recall_score(Y_test_wine, Y_pred_wine, average=None))
print("\n\nF1 score:",f1_score(Y_test_wine, Y_pred_wine, average=None))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion matrix: 
 [[17  0  0]
 [25  0  0]
 [19  0  0]]


Accuracy: 0.2786885245901639


Precision: [0.27868852 0.         0.        ]

Recall: [1. 0. 0.]


F1 score: [0.43589744 0.         0.        ]


In [ ]:

#Without Encoding
X_train_w1, X_test_w1, Y_train_w1, Y_test_w1 = train_test_split(X_wine,
Y_wine, test_size = 0.34, random_state = 121)

#Train the model using the training sets
gnb.fit(X_train_w1, Y_train_w1)

#Predict the response for test dataset
Y_pred_w1 = gnb.predict(X_test_w1)



In [ ]:
print('Confusion matrix: \n', confusion_matrix(Y_test_w1,Y_pred_w1))
print("\n\nAccuracy:",accuracy_score(Y_test_w1, Y_pred_w1))
print("\n\nPrecision:",precision_score(Y_test_w1, Y_pred_w1, average=None))
print("\nRecall:",recall_score(Y_test_w1, Y_pred_w1, average=None))
print("\n\nF1 score:",f1_score(Y_test_w1, Y_pred_w1, average=None))

Confusion matrix: 
 [[16  1  0]
 [ 0 24  1]
 [ 0  0 19]]


Accuracy: 0.9672131147540983


Precision: [1.   0.96 0.95]

Recall: [0.94117647 0.96       1.        ]


F1 score: [0.96969697 0.96       0.97435897]
