In [1]:
import sys,os
import matplotlib.pyplot as plt
from sklearn import svm,metrics
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()
digits.data.shape

(1797, 64)

In [3]:
print(digits.target)

[0 1 2 ... 8 9 8]


In [5]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.25 ,random_state = 121)

#Linear Kernel

In [6]:
lsc = svm.SVC(kernel='linear')

In [7]:
lsc.fit(X_train,y_train)

SVC(kernel='linear')

In [8]:
y_predict_linear=lsc.predict(X_test)

In [19]:
print("Classification report: ", metrics.classification_report(y_test,y_predict_linear))
print("\nConfusion matrix: \n", metrics.confusion_matrix(y_test,y_predict_linear))
print("\n\nAccuracy: ", metrics.accuracy_score(y_test,y_predict_linear))

Classification report:                precision    recall  f1-score   support

           0       1.00      0.98      0.99        54
           1       1.00      1.00      1.00        42
           2       1.00      1.00      1.00        43
           3       1.00      0.93      0.96        42
           4       0.96      1.00      0.98        47
           5       0.93      0.98      0.95        43
           6       0.98      0.98      0.98        46
           7       1.00      1.00      1.00        42
           8       0.95      0.98      0.97        43
           9       0.98      0.96      0.97        48

    accuracy                           0.98       450
   macro avg       0.98      0.98      0.98       450
weighted avg       0.98      0.98      0.98       450


Confusion matrix: 
 [[53  0  0  0  1  0  0  0  0  0]
 [ 0 42  0  0  0  0  0  0  0  0]
 [ 0  0 43  0  0  0  0  0  0  0]
 [ 0  0  0 39  0  2  0  0  0  1]
 [ 0  0  0  0 47  0  0  0  0  0]
 [ 0  0  0  0  0 42  1  0  0  0

#RBF Kernel

In [13]:
svmRBF = svm.SVC(kernel='rbf')

In [14]:
svmRBF.fit(X_train,y_train)

SVC()

In [16]:
y_pred_RBF=svmRBF.predict(X_test)

In [20]:
print("Classification report: ", metrics.classification_report(y_test,y_pred_RBF))
print("\nConfusion matrix: \n", metrics.confusion_matrix(y_test,y_pred_RBF))
print("\n\nAccuracy: ", metrics.accuracy_score(y_test,y_pred_RBF))

Classification report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00        54
           1       1.00      1.00      1.00        42
           2       1.00      1.00      1.00        43
           3       1.00      0.95      0.98        42
           4       1.00      0.98      0.99        47
           5       0.98      0.98      0.98        43
           6       0.98      1.00      0.99        46
           7       1.00      1.00      1.00        42
           8       0.93      1.00      0.97        43
           9       1.00      0.98      0.99        48

    accuracy                           0.99       450
   macro avg       0.99      0.99      0.99       450
weighted avg       0.99      0.99      0.99       450


Confusion matrix: 
 [[54  0  0  0  0  0  0  0  0  0]
 [ 0 42  0  0  0  0  0  0  0  0]
 [ 0  0 43  0  0  0  0  0  0  0]
 [ 0  0  0 40  0  1  0  0  1  0]
 [ 0  0  0  0 46  0  0  0  1  0]
 [ 0  0  0  0  0 42  1  0  0  0

#Polynomial Kernel

In [21]:
svm_poly=svm.SVC(kernel='poly')

In [22]:
svm_poly.fit(X_train,y_train)

SVC(kernel='poly')

In [23]:
y_pred_poly=svm_poly.predict(X_test)

In [24]:
print("Classification report: ", metrics.classification_report(y_test,y_pred_poly))
print("\nConfusion matrix: \n", metrics.confusion_matrix(y_test,y_pred_poly))
print("\n\nAccuracy: ", metrics.accuracy_score(y_test,y_pred_poly))

Classification report:                precision    recall  f1-score   support

           0       1.00      0.98      0.99        54
           1       1.00      1.00      1.00        42
           2       1.00      1.00      1.00        43
           3       1.00      0.95      0.98        42
           4       0.98      1.00      0.99        47
           5       0.95      0.98      0.97        43
           6       0.98      0.98      0.98        46
           7       1.00      1.00      1.00        42
           8       0.96      1.00      0.98        43
           9       1.00      0.98      0.99        48

    accuracy                           0.99       450
   macro avg       0.99      0.99      0.99       450
weighted avg       0.99      0.99      0.99       450


Confusion matrix: 
 [[53  0  0  0  1  0  0  0  0  0]
 [ 0 42  0  0  0  0  0  0  0  0]
 [ 0  0 43  0  0  0  0  0  0  0]
 [ 0  0  0 40  0  2  0  0  0  0]
 [ 0  0  0  0 47  0  0  0  0  0]
 [ 0  0  0  0  0 42  1  0  0  0

In [ ]:
#Linear: 0.98
#RBF: 0.9888888888888889
#Polynomial: 0.9866666666666667