In [1]:
!pip install tensorflow

     |████████████████████████████████| 462 kB 4.4 MB/s 


In [2]:
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [77]:
stopwords = [ "a", "about", "above", "after", "again", "against", "all", "am",
             "an", "and", "any", "are", "as", "at", "be", "because", "been", "before",
             "being", "below", "between", "both", "but", "by", "could", "did", "do",
             "does", "doing", "down", "during", "each", "few", "for", "from", "further",
             "had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here",
             "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i",
             "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its",
             "itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on",
             "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out",
             "over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so",
             "some", "such", "than", "that", "that's", "the", "their", "theirs", "them",
             "themselves", "then", "there", "there's", "these", "they", "they'd",
             "they'll", "they're", "they've", "this", "those", "through", "to", "too",
             "under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're",
             "we've", "were", "what", "what's", "when", "when's", "where", "where's",
             "which", "while", "who", "who's", "whom", "why", "why's", "with", "would",
             "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself",
             "yourselves" ]

In [78]:
import pandas as pd

In [79]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/spam2.csv")
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   v1      5572 non-null   object
 1   v2      5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [81]:
X = df['v2'].values
y = df['v1'].values


In [82]:
print(X)
print(type(X))

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 ... 'Pity, * was in mood for that. So...any other suggestions?'
 "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"
 'Rofl. Its true to its name']
<class 'numpy.ndarray'>


In [83]:
le=LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 0 1 ... 0 0 0]


#Defining Vectorizer unigram and bigram

In [84]:
cv1 = CountVectorizer(stop_words=stopwords)

cv2 = CountVectorizer(ngram_range=(2,2), stop_words=stopwords)

X1 = cv1.fit_transform(X)  #for unigram matching
X2 = cv2.fit_transform(X)  #for bigram matching

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:401: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['let', 'll', 're', 've'] not in stop_words.
  % sorted(inconsistent)


In [85]:
print(X1.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [86]:
print(X2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [87]:
cv1.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zoom', 'zouk', 'zyada'], dtype=object)

In [88]:
cv2.get_feature_names_out()

array(['00 easter', '00 per', '00 sub', ..., 'zoom cine', 'zouk nichols',
       'zyada kisi'], dtype=object)

In [90]:
X1.shape

(5572, 8513)

In [89]:
X2.shape

(5572, 32940)

#Naive Bayes

For unigram matching

In [91]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(X1,y,test_size = 0.2, random_state=121)

In [93]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train,y_train)

y_pred= model.predict(X_test)

In [94]:
from sklearn.metrics import confusion_matrix, classification_report

In [95]:
print("Confusion matrix: ")
print(confusion_matrix(y_test,y_pred))

print("\nClassification Report: ")
print(classification_report(y_test,y_pred))

Confusion matrix: 
[[959   8]
 [  8 140]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       967
           1       0.95      0.95      0.95       148

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



For bigram matching

In [96]:
X_train, X_test,y_train, y_test = train_test_split(X2,y,test_size = 0.2, random_state=121)

model = MultinomialNB()
model.fit(X_train,y_train)

y_pred= model.predict(X_test)

print("Confusion matrix: ")
print(confusion_matrix(y_test,y_pred))

print("\nClassification Report: ")
print(classification_report(y_test,y_pred))

Confusion matrix: 
[[800 167]
 [  5 143]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.99      0.83      0.90       967
           1       0.46      0.97      0.62       148

    accuracy                           0.85      1115
   macro avg       0.73      0.90      0.76      1115
weighted avg       0.92      0.85      0.87      1115



#Decision Tree

In [22]:
from sklearn.tree import DecisionTreeClassifier

For Unigram matching

In [101]:
#using entropy as criteria
X_train, X_test,y_train, y_test = train_test_split(X1,y,test_size = 0.2, random_state=121)
dt1 = DecisionTreeClassifier(criterion = 'entropy', random_state = 121)
dt1.fit(X_train, y_train)
y_pred1 = dt1.predict(X_test)

In [102]:
print("Confusion matrix: ")
print(confusion_matrix(y_test,y_pred1))

print("\nClassification Report: ")
print(classification_report(y_test,y_pred1))

Confusion matrix: 
[[959   8]
 [ 28 120]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       967
           1       0.94      0.81      0.87       148

    accuracy                           0.97      1115
   macro avg       0.95      0.90      0.93      1115
weighted avg       0.97      0.97      0.97      1115



In [109]:
#using gini index as criteria
X_train, X_test,y_train, y_test = train_test_split(X1,y,test_size = 0.2, random_state=121)
dt1 = DecisionTreeClassifier(criterion = 'gini', random_state = 121)
dt1.fit(X_train, y_train)
y_pred1 = dt1.predict(X_test)

In [110]:
print("Confusion matrix: ")
print(confusion_matrix(y_test,y_pred1))

print("\nClassification Report: ")
print(classification_report(y_test,y_pred1))

Confusion matrix: 
[[959   8]
 [ 28 120]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       967
           1       0.94      0.81      0.87       148

    accuracy                           0.97      1115
   macro avg       0.95      0.90      0.93      1115
weighted avg       0.97      0.97      0.97      1115



For bigram matching

In [105]:
#using entropy as criteria
X_train, X_test,y_train, y_test = train_test_split(X2,y,test_size = 0.2, random_state=121)
dt2 = DecisionTreeClassifier(criterion = 'entropy', random_state = 121)
dt2.fit(X_train, y_train)
y_pred2 = dt2.predict(X_test)

In [106]:
print("Confusion matrix: ")
print(confusion_matrix(y_test,y_pred2))

print("\nClassification Report: ")
print(classification_report(y_test,y_pred2))

Confusion matrix: 
[[963   4]
 [ 37 111]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       967
           1       0.97      0.75      0.84       148

    accuracy                           0.96      1115
   macro avg       0.96      0.87      0.91      1115
weighted avg       0.96      0.96      0.96      1115



In [107]:
#using gini index as criteria
X_train, X_test,y_train, y_test = train_test_split(X2,y,test_size = 0.2, random_state=121)
dt2 = DecisionTreeClassifier(criterion = 'gini', random_state = 121)
dt2.fit(X_train, y_train)
y_pred2 = dt2.predict(X_test)

In [108]:
print("Confusion matrix: ")
print(confusion_matrix(y_test,y_pred2))

print("\nClassification Report: ")
print(classification_report(y_test,y_pred2))

Confusion matrix: 
[[962   5]
 [ 36 112]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.96      0.99      0.98       967
           1       0.96      0.76      0.85       148

    accuracy                           0.96      1115
   macro avg       0.96      0.88      0.91      1115
weighted avg       0.96      0.96      0.96      1115

